In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import ttest_ind, ttest_rel, ttest_1samp, kstest, shapiro, pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# df1 =  pd.read_csv('1.csv',index_col=False)
# df1 = df1[df1['CLSTAR_COMPONENTS'] < 6]
# df1.to_csv("asd.csv")

In [3]:
# don't run this if you use google colab 
df1 =  pd.read_csv('1.csv',index_col=False)
df2 =  pd.read_csv('2.csv',index_col=False)
df3 =  pd.read_csv('3.csv',index_col=False)
df4 =  pd.read_csv('4.csv',index_col=False)
len(df1) + len(df2)

12

In [4]:
def f(df, num):
    for i in range(len(df['FILE_NAME'])):
        df['FILE_NAME'][i] = str(num)
        num += 1
    return num
        
num = 1
num = f(df1, num)
num = f(df2, num)
num = f(df3, num)
num = f(df4, num)

theDf = pd.concat([df1, df2, df3, df4], ignore_index=True, sort=False)
theDf

C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['FILE_NAME'][i] = str(num)
C:\Users\Aryan\AppData\Local\Temp\ipykernel_15148\38013149.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['FILE_NAME'][i] = str(num)

,FILE_NAME,STATES,INPUTS,LSTAR_MQ_SYM,LSTAR_MQ_RST,LSTAR_EQ_SYM,LSTAR_EQ_RST,LSTAR_TOTAL_SYM,LSTAR_TOTAL_RST,LSTAR_EQs,...,CLSTAR_MQ_RST,CLSTAR_EQ_SYM,CLSTAR_EQ_RST,CLSTAR_TOTAL_SYM,CLSTAR_TOTAL_RST,CLSTAR_EQs,CLSTAR_COMPONENTS,CLSTAR_ROUNDS,CLSTAR_MQs,CACHE
0,1,864,21,4397018,99029,74554,501,4471572,99530,2,...,214650,5352479,35719,22293042,250369,353,6,21,272890,True
1,2,1600,21,6591598,215974,74574,501,6666172,216475,2,...,253229,8364289,55822,29111396,309051,390,6,25,326113,True
2,3,864,21,10749466,506396,74928,501,10824394,506897,2,...,376006,12037143,80263,42894077,456269,490,6,30,482092,True
3,4,1280,21,6648933,145109,73621,501,6722554,145610,2,...,192306,4981105,33172,20842165,225478,338,6,21,244458,True
4,5,900,21,16189391,215579,75573,501,16264964,216080,2,...,223273,4670101,31188,21366966,254461,312,6,19,278242,True
5,6,1080,21,24689945,714131,75149,502,24765094,714633,3,...,368970,11652178,77749,40996057,446719,486,6,30,471781,True
6,7,1600,21,2757345,55771,75706,501,2833051,56272,2,...,70607,1370834,9135,7113968,79742,210,6,11,91975,True
7,8,2400,21,8018736,207910,74716,501,8093452,208411,2,...,237763,5276874,35195,24181457,272958,337,6,20,302658,True
8,9,1920,21,8890843,300099,74957,501,8965800,300600,2,...,291661,7761053,51706,30257304,343367,392,6,25,364955,True
9,10,360,21,9889905,100725,74690,501,9964595,101226,2,...,62164,1451568,9641,6206265,71805,209,6,11,78660,True
10,11,1080,21,14804961,323264,74537,502,14879498,323766,3,...,308855,8132297,54211,33694048,363066,411,6,26,397213,True
11,12,3840,36,19126140,332426,75538,501,19201678,332927,2,...,451994,7171372,47789,43862132,499783,720,8,26,538039,True
12,13,2160,36,9288140,172360,76864,501,9365004,172861,2,...,126145,2164736,14406,11360928,140551,477,8,15,152937,True

In [5]:
theDf.to_csv("Results.csv")